# Generated by Django 3.2.7 on 2021-09-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210903_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
