# Generated by Django 3.2.7 on 2021-09-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
